clean up ruby-ctags script a bit

diff --git a/bin/ctags-ruby b/bin/ctags-ruby
--- a/bin/ctags-ruby
+++ b/bin/ctags-ruby
@@ -1,13 +1,14 @@
 #!/bin/sh
-# Usage: ctags-ruby
-# Build ruby ctags file in current directory. Requires
-# exuberant ctags to be installed:
-# http://ctags.sourceforge.net/
+# Usage: ctags-ruby [<options>]
+# Build tags file in current directory. Any <options> provided are passed to
+# ctags. Requires exuberant ctags.
 set -e
-ctags -f tags                          \
-    --recurse                          \
-    --extra=+f                         \
-    --links=yes                        \
-    --tag-relative=yes                 \
-    --totals=yes                       \
-    --regex-ruby='/.*alias(_method)?[[:space:]]+:([[:alnum:]_=!?]+),?[[:space:]]+:([[:alnum:]_=!]+)/\\2/f/'
+
+ctags --version >/dev/null 2>&1 || {
+    echo "ctags not found or too old." 1>&2
+    exit 1
+}
+
+RUBYALIAS='/.*alias(_method)?[[:space:]]+:([[:alnum:]_=!?]+),?[[:space:]]+:([[:alnum:]_=!]+)/\\2/f/'
+ctags -R --tag-relative=yes --totals=yes \
+    --extra=+f --fields=+iaS --regex-ruby="$RUBYALIAS" "$@"
