github-open handles more weird cases

diff --git a/bin/github-open b/bin/github-open
--- a/bin/github-open
+++ b/bin/github-open
@@ -1,5 +1,5 @@
 #!/bin/sh
-#
+
 ## Usage: github-open FILE [LINE]
 ## Open GitHub file/blob page for FILE on LINE. FILE is the path to the
 ## file on disk; it must exist and be tracked with the current HEAD
@@ -13,7 +13,8 @@
 ##
 ## Open current file in vim on line 20:
 ##   :!github-open % 20
-#
+
+set -e
 
 FILE="$1"
 LINE="$2"
@@ -22,6 +23,12 @@ LINE="$2"
 test -z "$FILE" -o "$FILE" = '--help' && {
   cat "$0" | grep '^##' | cut -c4- 1>&2
   exit 1
+}
+
+# bail out with message to stderr and exit status 1
+die() {
+    echo "$(basename $0):" "$@" 1>&2
+    exit 1
 }
 
 # figure out relative path to the file from the root
@@ -38,12 +45,38 @@ do
   cd ..
 done
 
+# get the current branch in refs/heads/<branch> form
+ref=$(git symbolic-ref -q HEAD)
+test -n "$ref" ||
+die "you're not on a branch"
+
+# just the branch name please
+branch=$(echo "$ref" | sed 's@^refs/heads/@@')
+test -n "$branch" ||
+die "you're in a weird place; get on a local branch"
+
+# remote we're tracking
+remote=$(git config --get "branch.$branch.remote" || true)
+test -n "$remote" ||
+die "you're not tracking a remote branch"
+
+# remote branch we're tracking
+merge=$(
+    (git config --get "branch.$branch.merge") |
+    sed 's@refs/heads/@@'
+)
+test -n "$merge" ||
+die "you're not tracking a remote branch"
+
 # at this point we're in root of the work tree and $path is
 # the relative path to file.
-ref=$(git rev-parse origin)
-remote=$(git config --get remote.origin.url)
-repo=$(echo $remote | sed 's/^.*:\(.*\)\.git/\1/')
-url="http://github.com/$repo/blob/$ref/$path"
+remote_url=$(git config --get remote.$remote.url)
+repo=$(echo "$remote_url" | sed 's/^.*:\(.*\)\.git/\1/')
+url="http://github.com/$repo/blob/$branch/$path"
+
+# debugging
+# echo "url: $remote_url"
+# echo "repo: $repo"
 
 # throw the line number on there if specified
 test -n "$LINE" && url="$url#L$LINE"
