pbindent -o writes to stdout instead of back to pboard

diff --git a/bin/pbindent b/bin/pbindent
--- a/bin/pbindent
+++ b/bin/pbindent
@@ -1,5 +1,19 @@
 #!/bin/sh
-# Usage: pbindent
-# Indent pboard text four spaces.
+# Usage: pbindent [-o]
+# Indent pboard text four spaces and update pboard with result. With -o,
+# write result to standard output instead of to the pboard.
 
-pbpaste | sed 's/^/    /' | pbcopy
+writer='pbcopy'
+while test $# -gt 0
+do
+    case "$1" in
+    -o)     writer='cat'
+            shift;;
+    --help) grep '^# ' $0 | cut -c3-
+            exit 0;;
+    *)      echo "$(basename $0): invalid argument: '$1'"
+            exit 1;;
+    esac
+done
+
+pbpaste | sed 's/^/    /' | $writer
